AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task API using API Gateway, Lambda, and DynamoDB

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 128

Resources:
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TasksTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/createTask/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        CreateTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/listTasks/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        ListTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: get

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/getTask/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        GetTask:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: get

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/updateTask/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        UpdateTask:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/deleteTask/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Environment:
        Variables:
          TABLE_NAME: !Ref TasksTable
      Events:
        DeleteTask:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete

Outputs:
  ApiBaseUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
